---
# tasks file for webservers
- name: Perform updates and install apache2
  apt:
    name: apache2
    state: absent
    update_cache: yes
- name: Insert new homepage index.html
  copy:
    src: index.html
    dest: /var/www/html
    owner: devasc
    mode: '0444'
