---
- name: CONFIGURE IPv6 ADDRESSING
  hosts: CSR1kv
  gather_facts: false
  connection: local
  
  tasks:
   - name: DELETE INTERFACE LOOPBACK
     ios_config:
       lines:
         - no int loopback 10
   
   - name: SHOW IPv6 INTERFACE BRIEF
     ios_command:
       commands:
         - show ipv6 interface brief
     register: output

   - name: SAVE OUTPUT ./ios_configurations/
     copy:
        content: "{{ output.stdout[0] }}"
        dest: "ios_configurations/IPv6_output_{{ inventory_hostname }}.txt"

